name: hello world 
on: push
jobs:
  my-job:
   runs-on: ubuntu-latest
   steps:
     - name: my step
       run: |
         echo "hello world!"
         pwd
         ls -la
         exit 1
       continue-on-error: true
   
     - name: runs on failure
       if: failure()
       run: echo "step is failed"
     - name: runs on success
       if: success()
       run: echo "pipeline is working"
