name: hello world 
on: push
jobs:
  my-job:
   runs-on: ubuntu-latest
   steps:
     - name: my step
       run: |
         echo "hello world!"
         pwd
         ls -la
       continue-on-error: false
     - if: failure()
       run: echo "step is failed"
     - if: success()
       run: echo "pipeline is working"
