name: hello world 
on: push
jobs:
  my-job:
   runs-on:
     - ubuntu-latest
   steps:
     - name: my step
       run: |
         echo "hello world!"
         pwd
         ls -la
         exit 1
   if: endsWith(0) == failure()
