name: for multi jobs run 
on: push

jobs:
  builds:
   runs-on: ubuntu-latest
   steps:
     - name: for first ci build
       run: echo "buldind first application using ci"
       exit 1

  tests:
   runs-on: ubuntu-latest
   needs: builds
   steps:
     - name: for testing
       run: echo "testing first build application"


    
  
