name: for multi jobs run 
on: push

jobs:
  builds:
   runs-on: ubuntu-latest
   steps:
     - name: for first ci build
       run: echo "buldind first application using ci"

  tests:
   runs-on: ubuntu-latest
   needs: builds
   steps:
     - name: for testing
       run: echo "testing first build application"
  deploy:
   runs-on: ubuntu-latest
   needs: tests
   steps:
     - name: for deployment
       run: echo "application is deployed"

    
  
